[build]
base = "client"
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "20"

[functions]
# Path is relative to the base ("client"), so this resolves to client/netlify/functions
directory = "netlify/functions"
node_bundler = "esbuild"
